# Generated by Django 6.0.4 on 2026-04-18 18:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_key', models.CharField(default='localuser', max_length=120)),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('prompts', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='CopilotRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_key', models.CharField(default='localuser', max_length=120)),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('guid', models.CharField(blank=True, default='', max_length=64)),
                ('run_id', models.CharField(blank=True, default='', max_length=64)),
                ('prompt', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='queued', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('timestamp_utc', models.CharField(blank=True, default='', max_length=64)),
                ('uploaded_files', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PromptPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_utc', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_utc', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CopilotDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('disk_filename', models.CharField(max_length=255)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='copilot_chat.copilotrun')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('text', models.TextField()),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='copilot_chat.promptpack')),
            ],
            options={
                'ordering': ['pack', 'order'],
            },
        ),
    ]
