# Generated by Django 6.0.4 on 2026-04-18 00:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TachyonPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('preset_id', models.CharField(max_length=64)),
                ('default_model_id', models.CharField(default='gpt5.1', max_length=80)),
                ('parameters', models.JSONField(default=dict)),
                ('system_instruction', models.TextField(default='Please answer the given questions based on the context provided.')),
                ('enabled', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('owner_team', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
