# Generated by Django 6.0.4 on 2026-04-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OncallChangeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_number', models.CharField(db_index=True, max_length=32)),
                ('sys_id', models.CharField(blank=True, max_length=64)),
                ('short_description', models.CharField(blank=True, max_length=512)),
                ('risk', models.CharField(blank=True, max_length=32)),
                ('assignment_group', models.CharField(blank=True, max_length=128)),
                ('cmdb_ci', models.CharField(blank=True, db_index=True, max_length=128)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('window_label', models.CharField(blank=True, max_length=64)),
                ('ai_outage_likely', models.CharField(choices=[('unknown', 'Unknown'), ('yes', 'Outage likely'), ('no', 'No outage'), ('maybe', 'Possible outage')], default='unknown', max_length=16)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_run_at', models.DateTimeField(blank=True, null=True)),
                ('ai_payload_json', models.TextField(blank=True)),
                ('matched_app', models.CharField(blank=True, max_length=256)),
                ('matched_impact', models.TextField(blank=True)),
                ('matched_emails', models.TextField(blank=True)),
                ('matched_suppr_ids', models.TextField(blank=True)),
                ('matched_banner', models.BooleanField(default=False)),
                ('matched_banner_msg', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('pulled', 'Pulled'), ('ai_reviewed', 'AI reviewed'), ('decided', 'Decided'), ('comms_drafted', 'Comms drafted'), ('comms_sent', 'Comms sent'), ('suppressions_done', 'Suppressions done'), ('banner_posted', 'Banner posted'), ('closed', 'Closed')], db_index=True, default='pulled', max_length=32)),
                ('comments', models.TextField(blank=True)),
                ('email_drafted_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('suppressions_done_at', models.DateTimeField(blank=True, null=True)),
                ('banner_posted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scheduled_start', '-created_at'],
                'indexes': [models.Index(fields=['stage'], name='servicenow__stage_2531ca_idx'), models.Index(fields=['ai_outage_likely'], name='servicenow__ai_outa_8f5e9d_idx'), models.Index(fields=['scheduled_start'], name='servicenow__schedul_dbfbca_idx')],
                'constraints': [models.UniqueConstraint(fields=('change_number', 'window_start', 'window_end'), name='uniq_change_per_window')],
            },
        ),
    ]
