# Generated by Django 6.0.4 on 2026-04-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncallchangereview',
            name='matched_notify_partners',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oncallchangereview',
            name='matched_suppression',
            field=models.TextField(blank=True),
        ),
    ]
