# Generated by Django 6.0.4 on 2026-04-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0002_oncallchangereview_matched_notify_partners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncallchangereview',
            name='actual_outcome',
            field=models.CharField(blank=True, choices=[('', 'Not yet (in-flight or upcoming)'), ('success', 'Successful'), ('partial', 'Successful with issues'), ('failed', 'Failed'), ('rolled_back', 'Rolled back'), ('aborted', 'Aborted / cancelled')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='oncallchangereview',
            name='checklist_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oncallchangereview',
            name='content_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oncallchangereview',
            name='content_summary_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oncallchangereview',
            name='issues_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oncallchangereview',
            name='outage_declared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oncallchangereview',
            name='outage_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oncallchangereview',
            name='outage_record_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='oncallchangereview',
            name='outage_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
