# Generated by Django 6.0.4 on 2026-04-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0003_oncallchangereview_actual_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncallchangereview',
            name='approval_feedback_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oncallchangereview',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oncallchangereview',
            name='approved_by',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='oncallchangereview',
            name='cr_approval_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_review', 'In review'), ('awaiting_requestor', 'Awaiting requestor'), ('ready_to_approve', 'Ready to approve'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='not_started', max_length=32),
        ),
        migrations.AddField(
            model_name='oncallchangereview',
            name='cr_review_ctask_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oncallchangereview',
            name='cr_review_ctask_number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
