# Generated by Django 6.0.4 on 2026-04-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0004_oncallchangereview_approval_feedback_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncallchangereview',
            name='pull_purpose',
            field=models.CharField(choices=[('outage_triage', 'Outage triage'), ('cr_approval', 'CR approval'), ('both', 'Both')], db_index=True, default='outage_triage', max_length=32),
        ),
    ]
