# Generated by Django 6.0.4 on 2026-05-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0005_oncallchangereview_pull_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeIntakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_template', models.CharField(db_index=True, default='epsilon', max_length=64)),
                ('uploaded_file', models.FileField(upload_to='servicenow_excel_uploads/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('parsed_payload_json', models.TextField(blank=True)),
                ('proposals_json', models.TextField(blank=True)),
                ('ai_completeness_json', models.TextField(blank=True)),
                ('ai_field_debug_json', models.TextField(blank=True)),
                ('submit_status', models.CharField(choices=[('draft', 'Draft'), ('submitting', 'Submitting'), ('cr_created', 'CR created'), ('xlsx_attached', 'Spreadsheet attached'), ('ctask_created', 'CTASK created'), ('done', 'Done'), ('error', 'Error')], db_index=True, default='draft', max_length=32)),
                ('submit_error', models.TextField(blank=True)),
                ('created_chg_number', models.CharField(blank=True, max_length=32)),
                ('created_chg_sys_id', models.CharField(blank=True, max_length=64)),
                ('created_ctask_number', models.CharField(blank=True, max_length=32)),
                ('created_ctask_sys_id', models.CharField(blank=True, max_length=64)),
                ('submit_task_id', models.CharField(blank=True, max_length=64)),
                ('completeness_task_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
