# Generated by Django 6.0.4 on 2026-05-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0006_changeintakerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_template', models.CharField(db_index=True, max_length=64, unique=True)),
                ('defaults_json', models.TextField(blank=True, default='{}', help_text='JSON dict {target_field: default_value}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vendor_template'],
            },
        ),
    ]
