# Generated by Django 6.0.4 on 2026-05-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0008_seed_epsilon_vendor_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('table', models.CharField(default='incident', max_length=80)),
                ('query', models.TextField(blank=True, help_text='ServiceNow encoded query.')),
                ('fields', models.TextField(blank=True, help_text='Comma-separated ServiceNow field names to return.')),
                ('row_limit', models.PositiveIntegerField(default=100)),
                ('actions_json', models.TextField(blank=True, default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
