# Generated by Django 6.0.4 on 2026-05-20 18:28

from django.db import migrations, models


def backfill_domain(apps, schema_editor):
    """Set domain on any pre-existing Report rows from their table value."""
    Report = apps.get_model('servicenow', 'Report')
    Report.objects.filter(table='change_request').update(domain='change')
    Report.objects.exclude(table='change_request').update(domain='incident')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0009_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='domain',
            field=models.CharField(choices=[('change', 'Change'), ('incident', 'Incident')], db_index=True, default='incident', max_length=16),
        ),
        migrations.AddField(
            model_name='report',
            name='email_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='email_recipients',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(backfill_domain, noop),
    ]
