# Generated by Django 6.0.4 on 2026-05-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0010_report_domain_report_email_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='domain',
            field=models.CharField(choices=[('change', 'Change'), ('incident', 'Incident'), ('ctask', 'CTASK')], db_index=True, default='incident', max_length=16),
        ),
    ]
